namespace Helios.Game
{
    public enum InteractorType
    {
        BED,
        CHAIR,
        DEFAULT,
        SCOREBOARD,
        ROOMDIMMER,
        POST_IT,
        TELEPORTER,
        GATE,
        ROLLER,
        ONE_WAY_GATE,
        VENDING_MACHINE,
        DICE,
        LOVE_RANDOMIZER,
        TOTEM_PLANET,
        TOTEM_HEAD,
        TOTEM_LEG,
        TROPHY,
        PRESENT,
        STEP_LIGHT,
        DECORATION,
        FORTUNE,
        LERT,
        MANNEQUIN,
        GUILD,
        GUILD_GATE
    }
}
